### ISSUE TITLE
Cannot import from mobile

### ISSUE THREAD

**Issue by etheric42** [xwingtabled/XwingTabled#15]
When using chrome on Android phone, I can paste the XWS from Launchbaynext, but there is no way to confirm the selection and import. I tried in both normal mode and desktop mode.

**Comment by jychuah** [comment]
Can you reply to this with your XWS from Launch Bay Next?

**Comment by etheric42** [comment]
{"name":"Y
Squad","description":"","faction":"rebelalliance","points":483,"version":"2.14.48","pilots":[{"id":"norrawexley-btla4ywing","ship":"btla4ywing","points":77,"upgrades":{"astromech":["r4astromech"],"command":["veteranwingleader"],"device":["protonbombs"],"gunner":["ezrabridger"],"modification":["afterburners"],"talent":["experthandling"],"turret":["ioncannonturret"]}},{"id":"graysquadronbomber","ship":"btla4ywing","points":45,"upgrades":{"gunner":["veteranturretgunner"],"turret":["ioncannonturret"]}},{"id":"graysquadronbomber","ship":"btla4ywing","points":45,"upgrades":{"gunner":["veteranturretgunner"],"turret":["ioncannonturret"]}},{"id":"graysquadronbomber","ship":"btla4ywing","points":45,"upgrades":{"gunner":["veteranturretgunner"],"turret":["ioncannonturret"]}},{"id":"graysquadronbomber","ship":"btla4ywing","points":45,"upgrades":{"gunner":["veteranturretgunner"],"turret":["ioncannonturret"]}},{"id":"echobaseevacuees","ship":"gr75mediumtransport","points":85,"upgrades":{"cargo":["tibannareserves","boostedscanners"],"hardpoint":["ioncannonbattery"],"team":["commsteam","damagecontrolteam"],"title":["quantumstorm"]}},{"id":"thanekyrell","ship":"t65xwing","points":57,"upgrades":{"command":["veteranwingleader"],"configuration":["servomotorsfoils"],"modification":["afterburners"],"talent":["crackshot"]}},{"id":"redsquadronveteran","ship":"t65xwing","points":42,"upgrades":{"configuration":["servomotorsfoils"],"talent":["crackshot"]}},{"id":"redsquadronveteran","ship":"t65xwing","points":42,"upgrades":{"configuration":["servomotorsfoils"],"talent":["crackshot"]}}],"vendor":{"lbn":{"builder":"Launch
Bay Next","builder_url":"https://launch-bay-next.herokuapp.com","link":"
https://launch-bay-next.herokuapp.com/print?lbx='Y%20Squad'.483.1.1.(12.13.(10.284).(98.'veteranwingleader').(12.394).(16.320).(14.294).(1.234).(4.261)).(12.18.(16.281).(4.261)).(12.18.(16.281).(4.261)).(12.18.(16.281).(4.261)).(12.18.(16.281).(4.261)).('gr75mediumtransport'.'echobaseevacuees'.(99.'tibannareserves'.'boostedscanners').(97.'ioncannonbattery').(96.'commsteam'.'damagecontrolteam').(15.'quantumstorm')).(33.3.(98.'veteranwingleader').(18.333).(14.294).(1.230)).(33.10.(18.333).(1.230)).(33.10.(18.333).(1.230))
"}}}

**Comment by jychuah** [comment]
A couple issues here:

- XwingTabled doesn't support huge ships/epic, unfortunately. I'd like to build in support (especially due to the wing mechanic), but until there's an FFG app that supports epic I can't do it. XwingTabled depends on the official app's metadata.
- Launch Bay Next appears to have given you an invalid XWS. It's inserting some newline characters where there shouldn't be any.

My suggestion is importing only the non-epic ships via the LaunchBayNext print URL and seeing if that works.
