### ISSUE TITLE
No internet connection error

### ISSUE THREAD

**Issue by ostar1295** [xwingtabled/XwingTabled#39]
Hi,

The link: https://xwingtabled.github.io/

Always shows an error saying I have no internet connection but I actually have internet. Cant find a way to solve the issue.

Best,
Oscar

**Comment by illegalPointer** [comment]
Same deal, 

I believe the app is trying to download no longer existing resources maybe?

**Comment by jychuah** [comment]
Hi! Thanks for your interest in the app. Unfortunately, it's currently unmaintained after the switch from Fantasy Flight Games to Atomic Mass Games. (The Fantasy Flight data is no longer available.)
